<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Models\Bill;
use Illuminate\Http\Request;
use App\Models\Drug;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class TestController extends Controller
{
    //
    public function index() {
        return response()->json(['id'=>'ok']);
    }
    //
    public function autoGeneratePrice(Request $request) {
        $drug = Drug::find($request->q);
        return response()->json([$drug->GiaBan]);
    }
    //
    public function autoGenerateDiscount(Request $request) {
        $drug = Drug::find($request->q);
        return response()->json([$drug->ChietKhau]);
    }
    // 
    public function getUsersAndAdmins() {
        // return "ok";
        $admins = DB::table('admin_users')->get();
        $users = DB::table('users')->get();
        return response()->json(['num_users' => count($users), 'num_admins' => count($admins)]);
    }
    // 
    public function getBills(Request $request) {
        $start_date = strtotime($request->start_date);
        $end_date = strtotime($request->end_date);
        // return [date('Y-m-d', $start_date), date('Y-m-d', $end_date)];
        $bills = DB::table('hoadon')
                    ->select(DB::raw('DATE_FORMAT(hoadon.NgayThanhToan, \'%Y-%m\') as date'), DB::raw('sum(cthd.DonGia * cthd.SoLuong - cthd.ChietKhau) as price'))
                    ->join('cthd', 'cthd.bill_id', '=', 'hoadon.id')
                    ->whereRaw('NgayThanhToan >= ?', [date('Y-m-d', $start_date)])
                    ->whereRaw('NgayThanhToan <= ?', [date('Y-m-d', $end_date)])
                    ->whereRaw('TinhTrang = ?', ['Đã thanh toán'])
                    ->groupBy('date')
                    ->orderBy('date', 'asc')
                    ->get();
        return $bills;
    }
// 
    public function getAllDrugs(Request $request) {
        $drugs = DB::table('thuoc')
        ->join('nhomthuoc', 'thuoc.drug_group_id', '=', 'nhomthuoc.id')
        ->get();
        return response()->json($drugs);
    }
    // 
    public function getDrugsWithDrugGroup(Request $request) {
        $drug_group_id = $request->id;
        $drugs = DB::table('thuoc')
        ->join('nhomthuoc', 'thuoc.drug_group_id', '=', 'nhomthuoc.id')
        ->where('drug_group_id', $drug_group_id)->get();
        return response()->json($drugs);
    }
    // 
    public function getTopFourNewDrugs(){
        $drugs = DB::table('thuoc')
        ->join('nhomthuoc', 'thuoc.drug_group_id', '=', 'nhomthuoc.id')
        ->orderBy('thuoc.created_at', 'asc')
        ->limit(4)
        ->get();
        return response()->json($drugs);
    }
// 
    public function getUser(Request $request) {
        $email = $request->email;
        $password = $request->password;
        $user = User::where([['email','=', $email], ['password', '=', $password]])->get();
        return response()->json($user[0]);
    }
}
