<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Models\Bill;
use Illuminate\Http\Request;
use App\Models\Drug;
use App\Models\ReceiptDetail;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use PhpParser\Node\Stmt\TryCatch;

class TestController extends Controller
{
    //
    public function index()
    {
        return response()->json(['id' => 'ok']);
    }
    //
    public function autoGeneratePrice(Request $request)
    {
        $drug = Drug::find($request->q);
        return response()->json([$drug->GiaBan]);
    }
    //
    public function autoGenerateDiscount(Request $request)
    {
        $drug = Drug::find($request->q);
        return response()->json([$drug->ChietKhau]);
    }
    // 
    public function getUsersAndAdmins()
    {
        // return "ok";
        $admins = DB::table('admin_users')->get();
        $users = DB::table('users')->get();
        return response()->json(['num_users' => count($users), 'num_admins' => count($admins)]);
    }
    // 
    public function getBills(Request $request)
    {
        $start_date = strtotime($request->start_date);
        $end_date = strtotime($request->end_date);
        // return [date('Y-m-d', $start_date), date('Y-m-d', $end_date)];
        $bills = DB::table('hoadon')
            ->select(DB::raw('DATE_FORMAT(hoadon.NgayThanhToan, \'%Y-%m\') as date'), DB::raw('sum(cthd.DonGia * cthd.SoLuong - cthd.ChietKhau) as price'))
            ->join('cthd', 'cthd.bill_id', '=', 'hoadon.id')
            ->whereRaw('NgayThanhToan >= ?', [date('Y-m-d', $start_date)])
            ->whereRaw('NgayThanhToan <= ?', [date('Y-m-d', $end_date)])
            ->whereRaw('TinhTrang = ?', ['Đã thanh toán'])
            ->groupBy('date')
            ->orderBy('date', 'asc')
            ->get();
        return $bills;
    }
    // 
    public function getAllDrugs(Request $request)
    {
        $drugs = DB::table('thuoc')
            ->join('nhomthuoc', 'thuoc.drug_group_id', '=', 'nhomthuoc.id')
            ->get();
        return response()->json($drugs);
    }
    // 
    public function getDrugsWithDrugGroup(Request $request)
    {
        $drug_group_id = $request->id;
        $name = $request->name;
        $drugs = DB::table('thuoc')
            ->selectRaw('thuoc.*, nhomthuoc.TenNhomThuoc')
            ->join('nhomthuoc', 'thuoc.drug_group_id', '=', 'nhomthuoc.id')
            ->whereRaw('nhomthuoc.TenNhomThuoc like ?', ['%' . $drug_group_id . '%'])
            ->whereRaw('thuoc.TenThuoc like ?', ['%' . $name . '%'])
            ->get();
        return response()->json($drugs);
    }
    // 
    public function getTopFourNewDrugs()
    {
        $drugs = DB::table('thuoc')
            ->join('nhomthuoc', 'thuoc.drug_group_id', '=', 'nhomthuoc.id')
            ->orderBy('thuoc.created_at', 'asc')
            ->limit(4)
            ->get();
        return response()->json($drugs);
    }
    // 
    public function getUser(Request $request)
    {
        $email = $request->email;
        $password = $request->password;
        $user = User::where([['email', '=', $email], ['password', '=', $password]])->get();
        if (count($user) > 0)
            return response()->json($user[0]);
        else
            return 'null';
    }
    // 
    public function registerAccount(Request $request)
    {
        try {
            //code...
            $user = new User;
            $user->first_name = $request->first_name;
            $user->last_name = $request->last_name;
            $user->province = $request->province;
            $user->district = $request->district;
            $user->ward = $request->ward;
            $user->detail_address = $request->detail_address;
            $user->email = $request->email;
            $user->email_verified_at = now();
            $user->password = $request->password;
            $user->save();
            return 'success';
        } catch (\Throwable $th) {
            //throw $th;
            return 'error';
        }
    }
    // 
    public function getDrugByID(Request $request) {
        $drug = Drug::find($request->id);

        $receipt_detail = DB::table('ctphieunhap')
        ->where('drug_id', $request->id)
        ->selectRaw(DB::raw('SUM(SoLuong) as TongSoLuong'))
        ->get();
        $num_input = ($receipt_detail[0]->TongSoLuong == null) ? 0 : intval($receipt_detail[0]->TongSoLuong);

        $detail_bill = DB::table('cthd')
        ->where('drug_id', $request->id)
        ->selectRaw(DB::raw('SUM(SoLuong) as TongSoLuong'))
        ->get();
        $num_output = ($detail_bill[0]->TongSoLuong == null) ? 0 : intval($detail_bill[0]->TongSoLuong);
        return response()->json(['drug_info' => $drug, 'sum' => $num_input - $num_output]);
    }
}
